Домашнее задание 1. Консольные посылки
anatolyul/lessons-java-liga-ru pull request #1
Opened 2024-12-15 12:31 UTC by anatolyul

2024-12-17 11:46 UTC, yuzanudenko commented
Папка console-packages не нужна, если конечно не собираешь делать модульный проект.
Нужно либо вынести всё в корень проекта, либо добавить конфиги для модульного проекта.

2024-12-17 11:51 UTC, yuzanudenko commented
В целом хороший проект.
Неплохая декомпозиция, наименования, используешь lombok (пусть и не везде уместно :)).

2024-12-17 12:13 UTC, yuzanudenko requested changes

2024-12-17 12:13 UTC, yuzanudenko commented on console-packages/src/main/java/ru/hofftech/model/Box.java
> +    String content;
! ВСЕ поля должны быть приватными и доступ к ним должен быть только через геттеры и сеттеры

2024-12-17 12:13 UTC, yuzanudenko commented on console-packages/src/main/java/ru/hofftech/model/Box.java
> +    public Box(int width, int height, String content) {
Тут конструктор можно сгенерировать lombok'ом

2024-12-17 12:13 UTC, yuzanudenko commented on console-packages/src/main/java/ru/hofftech/service/LoadingBoxesInTruckService.java
> +@RequiredArgsConstructor
По сути тут эта аннотация не нужна, у класса нет аргументов

2024-12-17 12:13 UTC, yuzanudenko commented on console-packages/src/main/java/ru/hofftech/service/LoadingBoxesInTruckService.java
> +    public void report(List<Truck> trucks) {
Наверное логичней было бы вынести этот метод в отдельный класс. Текущий же описывает алгоритмы, а вывод сюда не вписывается.

2024-12-17 12:13 UTC, yuzanudenko commented on console-packages/src/test/java/ru/hofftech/ApplicationTests.java
> +public class ApplicationTests {
Название не соответствует содержимому, по факту тестируются алгоритмы распределения, а не основной класс.

2024-12-17 13:35 UTC, anatolyul commented on console-packages/src/main/java/ru/hofftech/model/Box.java
> +    String content;
исправил.

2024-12-17 13:35 UTC, anatolyul commented on console-packages/src/main/java/ru/hofftech/model/Box.java
> +    public Box(int width, int height, String content) {
поставил конструктор, но потом оптимизировал и заменил на record (IDE подсказала)

2024-12-17 13:35 UTC, anatolyul commented on console-packages/src/main/java/ru/hofftech/service/LoadingBoxesInTruckService.java
> +@RequiredArgsConstructor
исправил

2024-12-17 13:36 UTC, anatolyul commented on console-packages/src/main/java/ru/hofftech/service/LoadingBoxesInTruckService.java
> +    public void report(List<Truck> trucks) {
исправил. вынес в класс ReportService

2024-12-17 13:36 UTC, anatolyul commented on console-packages/src/test/java/ru/hofftech/ApplicationTests.java
> +public class ApplicationTests {
скорректировал путь и название LoadingBoxesInTruckServiceTests

2024-12-17 18:21 UTC, yuzanudenko approved these changes

2024-12-18 07:56 UTC, boris-dev commented on console-packages/src/main/java/ru/hofftech/Application.java
> +package ru.hofftech;
Нет пакета проекта

2024-12-18 07:56 UTC, boris-dev commented on console-packages/src/main/java/ru/hofftech/controller/ConsoleController.java
> +                    LoadingBoxesInTruckService loadingBoxesInTruckService = new LoadingBoxesInTruckService();
Нужно инжектить через констуктор

2024-12-18 07:56 UTC, boris-dev commented on console-packages/src/main/java/ru/hofftech/controller/ConsoleController.java
> +                    if (command.equals("1")) {
Нужно придумать константы, но лучше енам так как это однородные константы

2024-12-18 07:56 UTC, boris-dev commented on console-packages/src/main/java/ru/hofftech/controller/ConsoleController.java
> +                    }
форматирование else нужно на той же строке

2024-12-18 07:56 UTC, boris-dev commented on console-packages/src/main/java/ru/hofftech/controller/ConsoleController.java
> +                if (command.equals("1") || command.equals("2"))
что если придёт 3? лучше выдать ошибку. И сделать блокпост чтобы убрать вложенность

2024-12-18 07:56 UTC, boris-dev commented on console-packages/src/main/java/ru/hofftech/controller/ConsoleController.java
> +                    ReportService.report(trucks);
переделать статику на класс и инжектить сервис в контроллер

2024-12-18 07:56 UTC, boris-dev commented on console-packages/src/main/java/ru/hofftech/controller/ConsoleController.java
> +                        trucks = loadingBoxesInTruckService.simpleAlg(boxes);
имеем две реализации алгоритма - вводим полиморфизм по интерфейсу алгоритмов погрузки

2024-12-18 07:56 UTC, boris-dev commented on console-packages/src/main/java/ru/hofftech/util/ImportBoxes.java
> +                        if (box.isValid()) {
А если не валидно то тихо пропускаем? Следуем - фейл фаст

2024-12-18 07:56 UTC, boris-dev commented on console-packages/src/main/java/ru/hofftech/model/Box.java
> +            log.warn("Skip Box {} not valid {} x {}",
Держим доменные объекты чистыми от лишних зависимостей. Систему логирования стараемся здесь не использовать. Только в сервисных и классов с другой логикой

2024-12-18 07:56 UTC, boris-dev commented on console-packages/src/main/java/ru/hofftech/model/Box.java
> +    public boolean isValid() {
Валидация оторвана от создания объекта, можно создать невалидный объект в системе

2024-12-18 07:56 UTC, boris-dev commented on console-packages/src/main/java/ru/hofftech/controller/ConsoleController.java
> +                String filePath = matcher.group(1);
логика парсинга непостредственно в контроллере, перенести в маппер или парсер команд или что-то такое

2024-12-18 07:56 UTC, boris-dev commented on console-packages/src/main/java/ru/hofftech/controller/ConsoleController.java
> +                boxes = parseFromFile(Objects.requireNonNull(getClass().getClassLoader().getResource(filePath)).getPath());
не статика - сделать отдельный класс и инжектить сюда

2024-12-18 07:56 UTC, boris-dev commented on console-packages/src/main/java/ru/hofftech/util/ImportBoxes.java
> +public class ImportBoxes {
парсер или ридер, сейчас в названии глагол

2024-12-18 07:56 UTC, boris-dev commented on console-packages/src/main/java/ru/hofftech/model/Truck.java
> +public class Truck {
интересный класс, очень ООП-шный и при этом хорошо тестируется - респект

2024-12-18 07:56 UTC, boris-dev commented on console-packages/src/main/java/ru/hofftech/service/ReportService.java
> +    public static void report(List<Truck> trucks) {
Нельзя легко протестировать. Ябы ввел ещё один класс - форматтер и траки на входе - стринг на выходе, тогда можно протестировать что мы выводим на консоль

2024-12-18 07:56 UTC, boris-dev commented on console-packages/src/test/java/ru/hofftech/service/LoadingBoxesInTruckServiceTests.java
> +public class LoadingBoxesInTruckServiceTests {
Tests -> Test

2024-12-22 15:14 UTC, anatolyul commented on console-packages/src/main/java/ru/hofftech/Application.java
> +package ru.hofftech;
исправил. добавил пакет.

2024-12-22 15:14 UTC, anatolyul commented on console-packages/src/main/java/ru/hofftech/controller/ConsoleController.java
> +                    LoadingBoxesInTruckService loadingBoxesInTruckService = new LoadingBoxesInTruckService();
исправил.

2024-12-22 15:14 UTC, anatolyul commented on console-packages/src/main/java/ru/hofftech/controller/ConsoleController.java
> +                    if (command.equals("1")) {
исправил. сделал через енам

2024-12-22 15:14 UTC, anatolyul commented on console-packages/src/main/java/ru/hofftech/controller/ConsoleController.java
> +                    }
исправил.

2024-12-22 15:14 UTC, anatolyul commented on console-packages/src/main/java/ru/hofftech/controller/ConsoleController.java
> +                if (command.equals("1") || command.equals("2"))
исправил.

2024-12-22 15:14 UTC, anatolyul commented on console-packages/src/main/java/ru/hofftech/controller/ConsoleController.java
> +                boxes = parseFromFile(Objects.requireNonNull(getClass().getClassLoader().getResource(filePath)).getPath());
исправил.

2024-12-22 15:14 UTC, anatolyul commented on console-packages/src/main/java/ru/hofftech/util/ImportBoxes.java
> +public class ImportBoxes {
исправил.

2024-12-22 15:15 UTC, anatolyul commented on console-packages/src/main/java/ru/hofftech/model/Truck.java
> +public class Truck {
спасибо

2024-12-22 15:15 UTC, anatolyul commented on console-packages/src/main/java/ru/hofftech/service/ReportService.java
> +    public static void report(List<Truck> trucks) {
исправил.

2024-12-22 15:15 UTC, anatolyul commented on console-packages/src/test/java/ru/hofftech/service/LoadingBoxesInTruckServiceTests.java
> +public class LoadingBoxesInTruckServiceTests {
исправил.

2024-12-25 11:29 UTC, merged